import { Inter } from "next/font/google";
import "./globals.css";
import NewNav from "@/Components/NewNav";
import Starfield from "@/Components/StarField";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body   >
    <NewNav/>
        {children}
        <Starfield
        starCount={5000}
        starColor={[255, 255, 255]}
        speedFactor={0.1}
        backgroundColor="black"
      />
        </body>
    </html>
  );
}
