import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/Components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-custom-background"  >
        <Navigation/>
        {children}
        </body>
    </html>
  );
}
