import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/Components/Navigation";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Historical Figures",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black" >
    <Navigation/>
        {children}
      
        </body>
    </html>
  );
}
